### PR TITLE
Add Rails 6.0 appraisal

### PR DESCRIPTION
**Pull request by HarlemSquirrel**

### CODE REVIEW

**Comment by HarlemSquirrel** [comment]
Here's the current problem

```
Bundler found conflicting requirements for the Ruby version:

  In rails_6.0.gemfile:

    Ruby

    nokogiri (>= 1.6.5) was resolved to 1.10.9, which depends on

      Ruby (>= 2.3.0)

    rails (~> 6.0.0) was resolved to 6.0.2.1, which depends on

      Ruby (>= 2.5.0)
```

**Comment by HarlemSquirrel** [comment]
Should we drop support for Ruby 2.3 and 2.4?

**Comment by HarlemSquirrel** [comment]
Also more important failures with Rails 6.0

```
Failures:

  1) AwesomerPrint/ActiveRecord ActiveRecord instance (raw) display single record

     Failure/Error: raw_object_string.sub!('?', '1992-10-10 12:30:00')

     

     NoMethodError:

       undefined method `sub!' for nil:NilClass

     # ./spec/ext/active_record_spec.rb:152:in `block (3 levels) in <top (required)>'

  2) AwesomerPrint/ActiveRecord ActiveRecord instance (raw) display multiple records

     Failure/Error: raw_object_string.sub!('?', '1992-10-10 12:30:00')

     

     NoMethodError:

       undefined method `sub!' for nil:NilClass

     # ./spec/ext/active_record_spec.rb:183:in `block (3 levels) in <top (required)>'
```

**Comment by paddor** [comment]
> Should we drop support for Ruby 2.3 and 2.4?

Drop 2.3 sure, but Ruby 2.4 is still officially supported until end of March 2020. Does supporting 2.4 hurt?

**Comment by HarlemSquirrel** [comment]
I'm fine supporting back to Ruby 2.3 as long as we can restrict the Rails 6 appraisal to Ruby >= 2.5 but I'm not sure how to do that.

**Comment by paddor** [comment]
Maybe in spec_helper.rb `exit if RUBY_VERSION < '2.5' && gemfile_used[/rails_(\d\.\d).gemfile/, 1] < '6.0'`? Not sure what `gemfile_used` would be, but maybe it's simply a `BUNDLER_` environment variable.

**Comment by HarlemSquirrel** [comment]
Travis does use the gemfiles configured for it so I think I've got it skipping Rails 6.0 for Ruby 2.3 and 2.4 now

**Pull request merged**
