### PR TITLE
Rename project to awesomer print

### PR DESCRIPTION
**Pull request by HarlemSquirrel**
- Rename `AwesomePrint` to `AwesomerPrint`
- Update TravisCI config to get all tests passing
- Add Ruby 2.6 and 2.7 to TravisCI config

### CODE REVIEW

**Comment by paddor** [comment]
Running `bundle` bring complains about `uninitialized constant AwesomerPrint`.

**Comment by HarlemSquirrel** [comment]
Looks like an issue with the rails_5.0.gemfile

**Comment by paddor** [comment]
I can't see the Travis CI setup script. But I just had to `sudo apt install libsqlite3-dev` on my Ubuntu to make `bundle install` happy.

**Comment by HarlemSquirrel** [comment]
Looks still broken after adding sqlite3 gem. Maybe we jsu remove that Rails 5 Gemfile since 5.1 and 5.2 seem to be working.

**Comment by paddor** [comment]
I have the same issue if I run `bundle exec rake`. Strange is that even after deleting `gemfiles/rails_5.0.gemfile*` and committing, the files are recreated when I run `bundle exec rake` and I can't see why.

**Comment by HarlemSquirrel** [comment]
> I have the same issue if I run `bundle exec rake`. Strange is that even after deleting `gemfiles/rails_5.0.gemfile*` and committing, the files are recreated when I run `bundle exec rake` and I can't see why.

That seems to be due to having this tool: https://github.com/thoughtbot/appraisal
I had to update Travis and remove the Rails 5.0 Gemfile

**Pull request merged**
