### PR TITLE
Add JRuby to TravisCI

### PR DESCRIPTION
**Pull request by HarlemSquirrel**

### CODE REVIEW

**Comment by paddor** [comment]
Sry, I’m on mobile. Can you fix the conflicts?

**Comment by HarlemSquirrel** [comment]
I can in a bit

**Comment by HarlemSquirrel** [comment]
Travis is passing, rerunning GH specs

**Comment by HarlemSquirrel** [comment]
I think we're all good!

**Comment by HarlemSquirrel** [comment]
Since it's passing like this, I think we're OK to leave the "hack" in there with a `FIXME` note.

**Pull request merged**
